# Generated by Django 5.0.6 on 2024-08-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_friendshipinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshipinvite',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Rejected')], default=0),
        ),
    ]
