# Generated by Django 5.0.6 on 2024-08-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_friendshipinvite_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshipinvite',
            name='status',
        ),
    ]
