# Generated by Django 5.0.6 on 2024-08-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_friendshipinvite_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshipinvite',
            options={'ordering': ['sent_from'], 'verbose_name': 'Приглашение в друзья', 'verbose_name_plural': 'Приглашения в друзья'},
        ),
    ]
